<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Update Stores Information");
?>

<div class="container">

<?
$sklad = Array(
Array (
        "TITLE" => "Нижний Новгород на Лескова",
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "4b3688d8-10af-11e8-80db-c86000606f92",
),

Array (
        "TITLE" => "Нижний Новгород на Бекетова",
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Нижний Новгород, ул. Бекетова, д. 15",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (831) 422–62–18",
        "SCHEDULE" => "",
        "XML_ID" => "38cb753a-88c3-11e8-80e4-c86000606f92",
),
Array (
        "TITLE" => "Нижний Новгород на Казанском шоссе",
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Нижний Новгород, Казанское шоссе, д. 6",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (831) 410–80–22",
        "SCHEDULE" => "",
        "XML_ID" => "84d58d66-88c5-11e8-80e4-c86000606f92",
),
Array (
        "TITLE" => "Нижний Новгород на Казанском шоссе",
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Нижний Новгород, ул. Культуры, д. 16",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (831) 225-38-67",
        "SCHEDULE" => "",
        "XML_ID" => "cd840965-b4d3-11e8-80eb-c86000606f92",
),
Array (
        "TITLE" => "Нижний Новгород на Ленина",
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Нижний Новгород, пр-т Ленина, д. 49В",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (831) 258-20-28",
        "SCHEDULE" => "",
        "XML_ID" => "88abc5c0-b724-11e8-80eb-c86000606f92",
),
Array (
        "TITLE" => "Владивосток на Корабельной Набережной",
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Владивосток, ул. Корабельная Набережная, д. 1, пом. 20",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (831) 258-20-28",
        "SCHEDULE" => "",
        "XML_ID" => "17f7624a-09fb-11ea-8101-c86000606f92",
),
Array (
        "TITLE" => '"Стрелок" г. Мурманск',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Мурманск, пр-т Ленина, д. 70",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "69cb9bd8-ecac-11e3-0196-c86000606f92",
),
Array (
        "TITLE" => '"Консул" г. Москва',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "3d92b51e-38b6-11e4-0684-c86000606f92",
),
Array (
        "TITLE" => '"Медведь" г. Йошкар-Ола',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Йошкар-Ола , ул. Суворова ,д. 19-Б",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (863) 230-40-24",
        "SCHEDULE" => "",
        "XML_ID" => "64b50e98-3d94-11e4-0e9c-c86000606f92",
),
Array (
        "TITLE" => '"Мушкет" г. Екатеринбург',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Екатеринбург, ул. Малышева, 31Д",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (343) 377-65-41",
        "SCHEDULE" => "",
        "XML_ID" => "e1997b58-e49b-11e3-178c-c86000606f92",
),
Array (
        "TITLE" => '"Беркут" г. Альметьевск',
        "ACTIVE" => "Y",
        "ADDRESS" => "Респ. Татарстан, г. Альметьевск, пр-т Строителей, д. 20В",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (917) 899-73-95",
        "SCHEDULE" => "",
        "XML_ID" => "8f1edb2e-53a5-11e4-1997-c86000606f92",
),
Array (
        "TITLE" => '"Сибирский калибр" г. Новокузнецк',
        "ACTIVE" => "Y",
        "ADDRESS" => "Кемеровская область, г. Новокузнецк, пр. Н.С. Ермакова, д. 30, корпус А",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "c8b911ce-74b1-11e4-2090-c86000606f92",
),
Array (
        "TITLE" => '"Ирбис" г. Ульяновск',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Ульяновск, ул. Минаева, д. 44/1",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (8422) 581-874",
        "SCHEDULE" => "",
        "XML_ID" => "23bee1ba-8f4d-11e4-2f98-c86000606f92",
),
Array (
        "TITLE" => '"Стерх" г. Саранск',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Саранск, ул. Коммунистическая, д. 35",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "ba9b7b20-31a1-11e4-4c86-c86000606f92",
),
Array (
        "TITLE" => '"Охотничьи традиции" г. Кострома',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "ad7e7966-cd7f-11e1-4d85-50e549b397c6",
),
Array (
        "TITLE" => '"Магнум" г. Тверь',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Тверь, Тверская площадь, д. 7",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "3427d668-7992-11e4-509f-c86000606f92",
),
Array (
        "TITLE" => '"Липецк-Актив" г. Липецк',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Липецк, ул. Пр. Победы д.124",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "73c7e84c-8173-11e4-509f-c86000606f92",
),
Array (
        "TITLE" => '"Ягуар" г.Самара',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "280b2abe-905a-4641-80d5-58b957fc4033",
),
Array (
        "TITLE" => '"Трофей" г. Иркутск',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "7381a6fa-7aff-4568-8149-a27171ea92b0",
),
Array (
        "TITLE" => '"Аты-Баты" г. Кострома',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Кострома, Красные ряды, д. 1",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "cff92538-4f37-4795-817f-2de3bfc7e8b5",
),
Array (
        "TITLE" => '"Кольт" г. Екатеринбург',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "133f2de2-c0e0-11e1-8380-50e549b397c6",
),
Array (
        "TITLE" => '"Тигр" г. Челябинск',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Челябинск, ул. Партизанская д. 32",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "1e8bba16-ea1f-11e3-869e-c86000606f92",
),
Array (
        "TITLE" => '"Соболь" г. Уфа',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "149e973f-418e-4fe1-8908-a88317ebbdcb",
),
Array (
        "TITLE" => '"Баллиста" г. Воронеж',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "cf74acc9-ebb2-41a4-897c-2d457b19dd53",
),
Array (
        "TITLE" => '"Зверобой" г.Ярославль',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Ярославль, ул. Гоголя, д. 2, ТЦ «Фараон»",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (4942) 624-601",
        "SCHEDULE" => "",
        "XML_ID" => "5166c33d-2959-4323-8be2-a17b6c0674cf",
),
Array (
        "TITLE" => '"Хантер" г. Казань',
        "ACTIVE" => "Y",
        "ADDRESS" => "Казань, Юлиуса Фучика, д. 90, оф. 100р",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "74fb13f9-f548-430e-8ce2-e45600a1db84",
),
Array (
        "TITLE" => '"Хантер" г. Набережные Челны',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Набережные Челны, пр-т Сююмбике, д. 9/26, 109 (41/05)",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (8552) 52-89-97",
        "SCHEDULE" => "",
        "XML_ID" => "c62fd75f-c258-4abf-8fc7-bbb4651ab21c",
),
Array (
        "TITLE" => '"Консул" г. Москва',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Москва, ул. Красная сосна, д. 2А",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (4942) 624–601",
        "SCHEDULE" => "",
        "XML_ID" => "f3efe58d-a023-440f-8fd9-ccd89a632f7e",
),
Array (
        "TITLE" => '"Бастион" г. Новосибирск',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "58c9e24a-457c-45f6-9190-6cf199580af7",
),
Array (
        "TITLE" => '"Охотничий домик" г. Кострома"',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Кострома, Пряничные ряды, пом. 266",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "c73c0bbe-12b4-4e88-9545-b589fad8eede",
),
Array (
        "TITLE" => '"Карабин" г. Иваново',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Иваново, ул. Лежневская, д. 55",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "d00ba26b-dcd4-4f1b-9660-93dd6b946832",
),
Array (
        "TITLE" => '"Хантер" г. Набережные Челны',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Набережные Челны, пр-т Сююмбике, д. 9/26, 109 (41/05)",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (8552) 52-89-97",
        "SCHEDULE" => "",
        "XML_ID" => "b67243d1-4a63-4fa1-9be3-1a0b6c1f6efe",
),
Array (
        "TITLE" => '"Наган" г. Екатеринбург',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "1dfab4e7-7f71-4550-9c0d-faea216db82e",
),
Array (
        "TITLE" => '"Тигр" г. Челябинск',
        "ACTIVE" => "Y",
        "ADDRESS" => "Челябинская обл., г. Челябинск, ул. Партизанская, д. 32",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "179f74ac-ea1c-11e3-9d8e-c86000606f92",
),
Array (
        "TITLE" => '"Росомаха" г. Сыктывкар',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "2ed648c5-017b-4750-9e93-82cc6a767e62",
),
Array (
        "TITLE" => '"Вепрь" г. Калуга',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Калуга, ул.Суворова, д. 121, пом.3",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "778dc3b1-c46a-4123-a09d-0c0df6ddd12f",
),
Array (
        "TITLE" => '"Следопыт" г. Кострома',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Кострома, ул. Молочная Гора, д. 4",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "c94d6ca8-1f8f-492f-a172-f7208fe5cc19",
),
Array (
        "TITLE" => '"Леон" г. Тюмень',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "871af989-f6ec-4076-a22f-fbbe2219264d",
),
Array (
        "TITLE" => '"Барс" г. Владимир',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "d3700ac8-c61e-4bf2-a3ec-7d8c09974689",
),
Array (
        "TITLE" => '"Кречет" г. Саратов',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Саратов, ул. Соколовая 10/16",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (452) 399-809",
        "SCHEDULE" => "",
        "XML_ID" => "ce3d89a0-3070-4d76-a53e-09fa3fc1f4d5",
),
Array (
        "TITLE" => "Н. Новгород Ленина",
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "87f3655d-3ccc-45f5-a70e-57f92d29c202",
),
Array (
        "TITLE" => '"Патриот" г. Улан-Удэ',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "5b7c4c8c-6314-4644-a8e7-0e76b7824bff",
),
Array (
        "TITLE" => "Н. Новгород Казанское",
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "337fbada-4a69-48ff-a960-552966d2eba0",
),
Array (
        "TITLE" => '"Ловчий" г. Курск',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Курск, ул. 50 лет Октября д. 3",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (903) 873-80-06",
        "SCHEDULE" => "",
        "XML_ID" => "0954ba84-314b-451b-aac4-7757a12da5e4",
),
Array (
        "TITLE" => '"Зверолов" г. Ковров',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "382554df-51a5-47fe-ac69-d07839d91950",
),
Array (
        "TITLE" => "Н. Новгород Лескова",
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "ee10dd60-a700-489c-ac7d-bb5504a74510",
),
Array (
        "TITLE" => '"Арсенал" г. Петрозаводск',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "8d39edce-2f94-4158-af09-7890183ccd6f2",
),
Array (
        "TITLE" => '"Бизон" г. Пенза',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Пенза, ул. Калинина, дом № 4",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "31ca54a4-b398-4c1e-b04a-18e3ee73750e",
),
Array (
        "TITLE" => '"Полигон" г. Кострома',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Кострома, ул. Советская, д. 113",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (4942) 32‒03‒31",
        "SCHEDULE" => "",
        "XML_ID" => "3a78034f-ec49-41a7-b0e3-10e9fa81a309",
),
Array (
        "TITLE" => '"Зубр" г. Санкт-Петербург',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "e515df40-89e7-4823-b26b-c3e4ceaee961",
),
Array (
        "TITLE" => '"Картечь" г. Новосибирск',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "350ffe62-84b0-43af-b2c7-adf8366871d3",
),
Array (
        "TITLE" => '"Тайга" г. Красноярск',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Красноярск, ул. Шахтёров, д. 16А",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "1de35f32-0cee-11e4-b397-c86000606f92",
),
Array (
        "TITLE" => '"Медвежий угол" г. Барнаул',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Барнаул, ул. Попова, д. 153В",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "ac6b7bf7-f4eb-4bcb-b3be-a71abe2c4e11",
),
Array (
        "TITLE" => '"ТТ" г. Тула',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Тула, ул. Болдина, д. 92, оф. 101",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "1d387d1c-05f2-4123-b459-21a1e792f258",
),Array (
        "TITLE" => '"Артемида" г. Иваново',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "e365450a-488e-4e36-b56b-7ea3b2823e2b",
),Array (
        "TITLE" => "Н. Новгород Сормово",
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "e2d59019-086b-44ac-b757-c5867e708ad5",
),
Array (
        "TITLE" => '"МЕЧ" г. Казань',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "bbb810af-6041-41f0-bb5f-9d8a4d1b0afd",
),
Array (
        "TITLE" => '"Снайпер" г. Ярославль',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Ярославль, пр-т Авиаторов, д. 149, пом. 2",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "29cd32c4-0c6c-43be-bb65-7f66df8ab0ce",
),
Array (
        "TITLE" => '"Охотничий домик" Титова г. Кострома',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "3729a1d9-5a06-492e-bb72-7998c52107c4",
),
Array (
        "TITLE" => '"Выстрел" г. Кострома',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Кострома, ул. Юбилейная, д. 28",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (4942) 624-632",
        "SCHEDULE" => "",
        "XML_ID" => "cfe0370c-3cf1-416d-bbcc-81175ee29548",
),
Array (
        "TITLE" => '"Кольт" г. Москва (МХМ)',
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "1c9db366-3069-4d75-bcfd-6e2f7852e042",
),
Array (
        "TITLE" => "Н. Новгород Бекетова",
        "ACTIVE" => "Y",
        "ADDRESS" => "",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "3934afd9-db2e-4e40-be95-232d6c1c8947",
),
Array (
        "TITLE" => '"Калибр" г. Санкт-Петербург',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Санкт-Петербург, ул. Типанова, д. 40 А",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "",
        "SCHEDULE" => "",
        "XML_ID" => "9e6471ab-3d71-4ff1-bfb4-67242783e299",
),
Array (
        "TITLE" => '"Гепард" г. Рязань',
        "ACTIVE" => "Y",
        "ADDRESS" => "г. Рязань, Московское шоссе, д. 5А, лит. А",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (4912) 777-199",
        "SCHEDULE" => "",
        "XML_ID" => "3c37c690-1c65-11e4-eb90-c86000606f92",
),
Array (
        "TITLE" => '"Арма" г. Стерлитамак',
        "ACTIVE" => "Y",
        "ADDRESS" => "Республика Башкортостан, Стерлитамакский район, село Мариинский, ул. Лазурная, д. 19А",
        "DESCRIPTION" => "",
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => "+7 (905) 000-12-34",
        "SCHEDULE" => "",
        "XML_ID" => "bc124ef8-4d25-11e4-fc93-c86000606f92",
),
    );

$c = 0;

while (count($sklad) > $c) {

$guid = $sklad[$c]['XML_ID'];
echo $guid."<br>";

$results = $DB->Query("SELECT ID FROM b_catalog_store WHERE XML_ID='$guid' LIMIT 1");

	while ($row = $results->Fetch())
	{
	if (isset($row['ID'])) {
	$arFields = Array(
        "TITLE" => $sklad[$c]['TITLE'],
        "ACTIVE" => "Y",
        "ADDRESS" => $sklad[$c]['ADDRESS'],
        "DESCRIPTION" => $sklad[$c]['DESCRIPTION'],
        "IMAGE_ID" => "",
        "GPS_N" => "",
        "GPS_S" => "",
        "PHONE" => $sklad[$c]['PHONE'],
        "SCHEDULE" => "",
        "XML_ID" => $sklad[$c]['XML_ID'],
    );    
    $ID = CCatalogStore::Update($row['ID'], $arFields);
	}
	}

$c++;

}

echo "<pre>";
print_r($sklad);
echo "</pre>";
/* *** */

?>

</div>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>